version: '3'
services:
  #Go App
  go-app:
    build: ./cmd
    container_name: projectx
    depends_on:
      - 'mongo'
    enviroment:
      - PORT=8000
    ports:
      - '8000:8000'
    volumes:
      -'./cmd:/opt/cmd:cached'
  mongo:
    image: 'mongo:4.2.6-bionic'
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/data/db"
    restart: always
 
   # Mongo Express Web-based MongoDB admin interface
  mongo_express:
      image: mongo-express
      container_name: mongo_express
      depends_on:
          - 'mongo'
      ports:
          - '8081:8081'
      restart: always
