version: '3'
services:
  #Go App
  go-app:
    build: ./
    command: ./projectx #run compile file
    container_name: projectx
    depends_on: #depends container; first mongo start
      - 'mongo'
    environment:
      - PORT=6969 # get env data os.LookUp
      # - hash_salt=salt_hash99
    ports:
      - '6969:6969'
  mongo:
    image: 'mongo:latest'
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/data/db"
    restart: always # start docker || restart computer -> mongo container
    environment:
      - USER_COLLECTION=users