package db

import (
	"database/sql"
	"log"
)

//set params outside
// func NewPostgresStorage(name, password, url, port, dbName string) *PostgreSql {}
// func (p *PostgreSql) InitPostgresDb() (*sql.DB, error) {}

type PostgreSqlDb struct {
	Config
}

func (p *PostgreSqlDb) InitDb() (interface{}, error) {
	log.Print(p.Config)
	db, err := sql.Open("postgres", "postgres://"+p.Config.user+":"+p.Config.password+"@"+p.Config.host+"/"+p.Config.dbName+"?sslmode=disable")
	if err != nil {
		return nil, err
	}
	if err = db.Ping(); err != nil {
		return nil, err
	}
	if err = createTables(db, p.Config.tableName); err != nil {
		return nil, err
	}
	return db, nil
}

func createTables(db *sql.DB, tableName string) error {
	linksTable, err := db.Prepare("CREATE TABLE IF NOT EXISTS " + tableName + `  (
		id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
		username varchar(255) NOT NULL UNIQUE,
		password varchar(255) NOT NULL
	)`)
	if err != nil {
		return err
	}
	linksTable.Exec()
	//etc tables create..

	return nil
}
